# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clients.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'clients.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rclients.proto\x12\x07\x63lients\"G\n\x06\x43lient\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tsobrenome\x18\x03 \x01(\t\x12\x10\n\x08telefone\x18\x04 \x01(\t\"H\n\x13\x43reateClientRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x11\n\tsobrenome\x18\x02 \x01(\t\x12\x10\n\x08telefone\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\".\n\nClientList\x12 \n\x07\x63lients\x18\x01 \x03(\x0b\x32\x0f.clients.Client2\x82\x01\n\rClientService\x12=\n\x0c\x43reateClient\x12\x1c.clients.CreateClientRequest\x1a\x0f.clients.Client\x12\x32\n\x0bListClients\x12\x0e.clients.Empty\x1a\x13.clients.ClientListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clients_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENT']._serialized_start=26
  _globals['_CLIENT']._serialized_end=97
  _globals['_CREATECLIENTREQUEST']._serialized_start=99
  _globals['_CREATECLIENTREQUEST']._serialized_end=171
  _globals['_EMPTY']._serialized_start=173
  _globals['_EMPTY']._serialized_end=180
  _globals['_CLIENTLIST']._serialized_start=182
  _globals['_CLIENTLIST']._serialized_end=228
  _globals['_CLIENTSERVICE']._serialized_start=231
  _globals['_CLIENTSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
