FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 50051

# O comando que será executado quando o contêiner iniciar
CMD ["python", "server.py"]